# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4.1'
  pod 'RealmSwift'
  pod 'SDWebImage', '~> 5.0'
  pod "PromiseKit", "~> 6.8"
  pod 'SwiftLint'
  # Pods for VKClient

end
